Fixed bugs in Debian init script

diff --git a/resources/init/debian b/resources/init/debian
--- a/resources/init/debian
+++ b/resources/init/debian
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 ### BEGIN INIT INFO
-# Provides:    	  inagent
+# Provides:    	     inagent
 # Required-Start:    $local_fs $remote_fs $network $syslog $named
 # Required-Stop:     $local_fs $remote_fs $network $syslog $named
 # Default-Start:     2 3 4 5
@@ -12,11 +12,11 @@
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DAEMON=/usr/local/bin/inagent
+PID=/run/inagent.pid
 NAME=inagent
 DESC=inagent
-PID=/run/inagent.pid
 
-if [-f /etc/lsb-release]
+if [ -f /etc/lsb-release ]; then
     STOP_SCHEDULE="TERM/30/KILL/5"
 else
     STOP_SCHEDULE="${STOP_SCHEDULE:-QUIT/5/TERM/5/KILL/5}"
@@ -29,74 +29,72 @@ test -x $DAEMON || exit 0
 
 do_start()
 {
-       	# Return
-       	#   0 if daemon has been started
-       	#   1 if daemon was already running
-       	#   2 if daemon could not be started
-       	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null \
-       		|| return 1
-       	start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON -- \
-       		$DAEMON_OPTS 2>/dev/null \
-       		|| return 2
+
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --test > /dev/null || return 1
+    start-stop-daemon --start --quiet --pidfile $PID --exec $DAEMON --background --make-pidfile 2>/dev/null || return 2
 }
 
 do_stop()
 {
-       	# Return
-       	#   0 if daemon has been stopped
-       	#   1 if daemon was already stopped
-       	#   2 if daemon could not be stopped
-       	#   other if a failure occurred
-       	start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
-       	RETVAL="$?"
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=$STOP_SCHEDULE --pidfile $PID --name $NAME
+    RETVAL="$?"
 
-       	sleep 1
-       	return "$RETVAL"
+    sleep 1
+    return "$RETVAL"
 }
 
 case "$1" in
-       	start)
-       		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
-       		do_start
-       		case "$?" in
-       			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-       			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-       		esac
-       		;;
-       	stop)
-       		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
-       		do_stop
-       		case "$?" in
-       			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-       			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
-       		esac
-       		;;
-       	restart)
-       		log_daemon_msg "Restarting $DESC" "$NAME"
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+		do_start
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+		;;
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
+		;;
+	restart)
+		log_daemon_msg "Restarting $DESC" "$NAME"
 
-       		do_stop
-       		case "$?" in
-       			0|1)
-       				do_start
-       				case "$?" in
-       					0) log_end_msg 0 ;;
-       					1) log_end_msg 1 ;; # Old process is still running
-       					*) log_end_msg 1 ;; # Failed to start
-       				esac
-       				;;
-       			*)
-       				# Failed to stop
-       				log_end_msg 1
-       				;;
-       		esac
-       		;;
-       	status)
-       		status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
-       		;;
-       	*)
-       		echo "Usage: $NAME {start|stop|restart|status}" >&2
-       		exit 3
-       		;;
+		do_stop
+		case "$?" in
+			0|1)
+				do_start
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+				;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+				;;
+		esac
+		;;
+	status)
+		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+		;;
+	*)
+		echo "Usage: $NAME {start|stop|restart|status}" >&2
+		exit 3
+		;;
 esac
 
 :
